### ISSUE TITLE
Freedesktop SDK 24.08 will be dropping appstream-compose

### ISSUE THREAD

**Issue by bbhtt** [flathub/org.gtk.Gtk3theme.Catppuccin-blue#1]
Please remove manual compose or switch to appstreamcli 

See https://docs.flatpak.org/en/latest/extension.html#extension-manifest for the commands

**Comment by Scrumplex** [comment]
This and the other repos are marked as EoL :O

**Comment by bbhtt** [comment]
> This and the other repos are marked as EoL :O

script doesn't take into account EOLs, if they were archived as per the policy it'd have worked. Anyway please ignore then.

**Comment by hfiguiere** [comment]
Where is it marked as EOL?

**Comment by Scrumplex** [comment]
Because these themes have undergone several name changes (or rather naming scheme changes) and I gave up trying to keep up

**Comment by hfiguiere** [comment]
I didn't ask why it was EOL. I asked where it was marked as EOL. Because it seems that there is no such indication as per 

https://docs.flathub.org/docs/for-app-authors/maintenance/#end-of-life

**Comment by Scrumplex** [comment]
Oh. I am sorry. Apparently I have done this for other themes, but not this one and its direct neighbors. Let me do that now, then!

**Comment by Scrumplex** [comment]
EOL. See #2
